# opt-in to Travis new container-based infrastructure
sudo: false

jdk: oraclejdk8
language: scala
scala: 2.11.6
env:
  global:
    - TRAVIS=true
    - TRAVIS_JVM_OPTS="-Xss6m -Xmx1560M -Xms1560M -client -Xverify:none -XX:MaxMetaspaceSize=512M"
before_install:
  - git submodule update --init --recursive
install:
  - sbt update
script:
  - cat /usr/lib/jvm/java-8-oracle/release
  - rm -rf tmp/nightly
  - mkdir -p tmp/nightly
  - cp .travis.sbt jvm/travis.sbt
  - ./nightly.sh sbt_task tortoiseJVM/test:compile "ensime generate"
  - ./nightly.sh sbt_test tortoiseJVM fast
  - ./nightly.sh sbt_test tortoiseJVM language
  - ./nightly.sh sbt_test tortoiseJS test
  - ./nightly.sh sbt_test tortoiseJVM crawl
  - travis_wait ./nightly.sh sbt_test netLogoWeb test
  - ./nightly.sh sbt_task tortoiseJVM/depend

after_failure:
  - dmesg | tail -100

notifications:
  hipchat:
    rooms:
      secure: "EEaRwfUUBj1phN/+8C3mbZARgSy3QWkx/ppQy/aBtydWpT82Mx3fhqOTKDpS3onEjioMqSOKzOGtQuZ1KP1agy11WDTFkwAhg9MMPzdc3J0gRaxhI6FyfZ9emWYmzM6GxGMtJZM1hOvenPp5QDQ7POyhCuQUW3+Utv2vQM3PkBg="
